# This workflow integrates a collection of open source static analysis tools with GitHub code scanning.
# For documentation, or to provide feedback, visit https://github.com/github/ossar-action
name: github/ossar-action

on: push

jobs:
  OSSAR-Scan:
    # OSSAR runs on windows-latest.
    # ubuntu-latest and macos-latest support coming soon
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

      # Install dotnet, used by OSSAR
    - name: Install .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

      # Run open source static analysis tools
    - name: Run OSSAR
      uses: github/ossar-action@main
      id: ossar

      # Upload results to the Security tab
    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
